name: Consistency proof

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

permissions: read-all

jobs:
  run_consistency_proof:
    permissions:
      contents: read
      issues: write
      id-token: write # Needed to detect the current reusable repository and ref
    uses: sigstore/rekor-monitor/.github/workflows/reusable_monitoring.yml@main
    with:
      file_issue: true